### ISSUE TITLE
Easy to read, up to date explanation of fields and descriptions

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight-schema#30]
I find myself wanting an easy to read up to date way to figure out what is currently in geoblacklight-schema. Does this make sense as a markdown file in the parent directory of this repository?

`schema.md`

**Comment by gravesm** [comment]
I think it would definitely be a good idea to have this somewhere. I guess another option would be to put it on the geoblacklight website. This is also related to #25.

**Comment by drh-stanford** [comment]
Yeah the only documentation right now is in our code4lib article. I think this is a common tool for harvesting/generating content so I can pull it out of the article and revise it as needed in a Wiki or .md.

**Comment by drh-stanford** [comment]
See #33 for documentation now

**Comment by drh-stanford** [comment]
i think this is fixed now with https://github.com/geoblacklight/geoblacklight-schema/blob/master/docs/geoblacklight-schema.markdown

Is there other documentation we've done?

**Comment by mejackreed** [comment]
Nope you are right! :+1:
