### ISSUE TITLE
Where should we be maintaining the XSL's were using?

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight-schema#43]
Currently xsl's are being used now in GeoCombine. Where should we maintain these long term?

**Comment by drh-stanford** [comment]
We can gem-ify geoblacklight-schema to make it more shareable if needed. The `gis-robot-suite` also uses the XSLTs via a git submodule.

The XSLTs that convert to/from geoblacklight could stay here long-term. OpenGeoMetadata is probably better for schema conversion XSLTs, maybe in a new repo explicitly for metadata/schema conversion. I dunno whether the OGP metadata WG has a github repo for metadata tools. It'd be nice to have a specific repo that others can use just to get the converters without needing other software to use them. People use all sorts of different software for XSLT conversions.

**Comment by mejackreed** [comment]
One concern I have about gemification, is what are we actually gemifying? A collection of shell and ruby scripts and xslt's? The schema validation used for geoblacklight-schema? How do all of these relate to eachother, and how do we semantically version it, test it?

**Comment by drh-stanford** [comment]
Yeah, that's why I've just been using git submodules. There isn't a Ruby API.

**Comment by drh-stanford** [comment]
Tracking in #70
