### ISSUE TITLE
Can we say that JSON is the preferred format?

### ISSUE THREAD

**Issue by mejackreed** [geoblacklight/geoblacklight-schema#51]
As Blacklight moves in the abstraction layer away from Solr, can we say that a core geoblacklight-schema document is just JSON?

**Comment by drh-stanford** [comment]
Yes, I think this is a good idea. I can change the export format to OpenGeoMetadata for edu.stanford.purl from XML to JSON.

**Comment by drh-stanford** [comment]
See https://github.com/sul-dlss/gis-robot-suite/issues/31

**Comment by drh-stanford** [comment]
Fixed in https://github.com/OpenGeoMetadata/edu.stanford.purl/pull/2

**Comment by mejackreed** [comment]
I'm going to say that this is resolved and that JSON is the preferred format.
