### ISSUE TITLE
Add support for ASCIIGRID

### ISSUE THREAD

**Issue by drh-stanford** [geoblacklight/geoblacklight-schema#65]
`iso2mods.xsl` should support `fileFormat = ASCIIGRID`

AAIGrid -- Arc/Info ASCII Grid

This format is the ASCII interchange format for Arc/Info Grid, and takes the form of an ASCII file, plus sometimes an associated .prj file. It is normally produced with the Arc/Info ASCIIGRID command.

@kimdurante what would the ISO metadata record have when the format is an Arc/Info ASCII Grid?

See https://github.com/geoblacklight/geoblacklight-schema/blob/master/lib/xslt/iso2mods.xsl#L54

**Comment by drh-stanford** [comment]
See 40f99b1 for a suggestion

**Comment by kimdurante** [comment]
The suggestion looks ok. However, ArcCatalog auto-generates the value 'Raster Dataset' for all raster formats. I will have to add a piece to the workflow that replaces this automated entry with a free text term. I have begun replacing these with GeoTIFF in cases where it's a GeoTIFF, but many legacy metadata will contain 'Raster Dataset.' If you want to use this tmethod, I will have to update the IBCAO records to contain there values. 

We could also explore the option of using the file extension, .tif, .asc, .shp to determine formats.

**Comment by kimdurante** [comment]
I have updated the format name to 'Arc/Info ASCII Grid' for these 2 layers:
yg482by7309
nq605vh1767

The xsl change you suggested should work for these. 
Going forward I will have to use a post-processing routine on the ArcGIS XML to map the formats to this field, or do it manually. As I mentioned, they all auto-generate as .Raster Dataset.'

We have 2 other new raster types in the pipeline .img and .ecw, so I will need to update those metadata before you accession them. I can do this today. I am thinking:

.img = ERDAS IMAGINE image file format
.ecw = Enhanced Compressed Wavelet

We can add these to the iso2mods.xsl if that works...

**Comment by kimdurante** [comment]
4a1c33819462626ebfd14bcbb948bc72cdb79400

I submitted a PR for this xsl - which should map the new MIME types as well
as output the PURL for digitized maps (in cases where there is a
georeferenced object)

**Comment by mejackreed** [comment]
Off topic... but at some point does it make sense to move some of this to GeoCombine? Or is too Stanford specific?

**Comment by kimdurante** [comment]
I am okay with moving this to GeoCombine. I am not sure if any others are
currently working with ISO2MODS transforms. There are some parts of the xsl
that might be SUL-specific but we could notate those if it helps...

**Comment by drh-stanford** [comment]
The repo's original purpose was for the Solr schema and the OGP ingest scripties. But I think now the geoblacklight-schema repo should be deprecated and its parts split up into GeoCombine and gis-robot-suite. Maybe leaving only schema validation and the OGP ingest scripties. I'd like to migrate the gazatteer code into its own gem, or maybe GeoCombine.

**Comment by mejackreed** [comment]
:+1:

**Comment by drh-stanford** [comment]
this PR is no longer valid
