### ISSUE TITLE
Represent original source of data for 'derived' datasets

### ISSUE THREAD

**Issue by sgbalogh** [geoblacklight/geoblacklight-schema#83]
I was just talking with @andrewbattista and Frank Donnelly (at CUNY Baruch) about this issue –– we have recently been discussing the best way to represent source material within a record. For instance, we have datasets that are submitted by researchers in which we would consider those researchers to be the creator, but in which the original data used may have come from another (or, often, multiple) source. Or there might be situations in which a GIS dataset was assembled from non-geocoded numeric data that had previously been published in a book, or found on a website.

What would be the best way to represent source materials, which do not neatly fit into creator or publisher? Is there a suitable key we could use in the `dct:references` document? Or perhaps we could start using `dc:source`? There is also `dc:relation`, I suppose, though to date we have only use this for related records on GeoNames.

**Comment by drh-stanford** [comment]
There is a dc:isVersionOf that might be appropriate. Relation is generic and isVersionOf is a refinement of that.

Thanks,
-Darren

**Comment by sgbalogh** [comment]
That sounds like it might be a good solution.

What do you think the best way to represent the values would be? It seems like we could go with either a URL of original resource (e.g. "mta.info"), a string representation of it (e.g. "Metropolitan Transit Authority"), or if the original version is in the catalog we could use the identifier for it.

**Comment by drh-stanford** [comment]
DC is generally not very prescriptive on the values. I would say URL or some other identifier would be best. A title may not be specific enough depending on your usage.

**Comment by drh-stanford** [comment]
See https://github.com/geoblacklight/geoblacklight/issues/412

**Comment by andrewbattista** [comment]
Consolidated
